TWITTER_KEY: CHthZe4965KtcB5PfaKzZ8WJ2
TWITTER_SECRET: WKp3m4kvjmnqWWjmTnLR94b3ZXTuNa1kayMF13GYM3XhL9WXKK
TWITTER_ACCESS_TOKEN: 627909509-po0YDzFq3lP8HuByDCz2JpNLdYEYZadxXKONrFUr
TWITTER_ACCESS_SECRET: K4jGu4sIcvnsNA6yeWlV3LOI7fqYzEas0oXUOr00Xbm00

TWILIO_SID: AC80f33a939838f5c451f17855aac99bb2
TWILIO_TOKEN: edbb9a708638fb1e38f15240a35ef9aa
TWILIO_PHONE_NUMBER: +1 501-251-6213

SKYLIGHT_ID: 9Xrscu64FLRd
SKYLIGHT_AUTH: JkDdLapEMkFAiDQsdIOxCdGyNtxnH-VFMFd-hrNeMu4

FEED_ENGINE_DATABASE_PASSWORD: jisahabitnunrabbit

# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
